version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "data-processing"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rwc7wduj6u7"
s3_prefix = "data-processing"
region = "eu-west-1"
profile = "yahoo-awscli"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
